/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.dansarie.jsnowball;

import org.junit.jupiter.api.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
    }
}
