/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.1/userguide/building_java_projects.html
 */

plugins {
    application
    id("com.xcporter.jpkg") version "0.0.8"
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.1")
    implementation("com.google.guava:guava:31.0.1-jre")
    implementation("org.apache.commons:commons-csv:1.9.0")
    implementation("org.json:json:20210307")
}

application {
    mainClass.set("se.dansarie.jsnowball.JSnowball")
}

jpkg {
    useVersionFromGit = false
    mainClass = "se.dansarie.jsnowball.JSnowball"
    packageName = "JSnowball"
    vendor = "Marcus Dansarie"
    copyright = "2021"
    menuGroup = "JSnowball"
    windows {
        winDirChooser = true
        winPerUser = true
        winMenu = true
        shortcut = true
    }
}